name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * 1,4"}]
  
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          extras_js: |
            document.querySelectorAll("h2")?.forEach(h2 => h2.remove())
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_gists: yes
          plugin_notable: yes
          plugin_reactions: yes
