name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_reactions: yes
      
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
  
